using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Lista_towarów
{
    public class Reader
    {
        //INDEKS;MAIN_PICTURE;PICTURES;ID_KARTOTEKI;NAZWA;KATEGORIE;EAN;
        //PRODUCENT;NA_MAGAZYNIE;STAN_NA_MAGAZYNIE;NA_ZAM;NA_PROMOCJI;ZAMIENNIKI;
        //CENA_KATALOGOWA;CENA_KLIENT;WALUTA;VAT;VAT_ODWR;RABAT_KLIENTA;WAGA;OPAKOWANIE;
        //JEDNOSTKA_MIARY;OPIS;SYMBOL_KATEGORII;DODANO;ZAKTUALIZOWANO;MIN_ZAM;CENA_KATALOGOWA_MIN;
        //JEDNOSTKA_MIARY_MIN;TYP_KURIERA;KURIERZY_NAZWA;KURIERZY_ID;ID_KAT;MAIN_PICTURE_REPLACE;
        //PICTURES_REPLACE;POZWOL_ZAMOWIC_BEZ_STANU;KROTKI_OPIS;CENA_KLIENT1;
        //CENA_KLIENTA_MIN;KOD_PRODUCENTA;ACTIVE																															
    }
}
